[package]
name = "rust-batcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
concurrent-queue = "2.3.0"
"futures" = "0.3"
rand = "0.8.5"
